### ISSUE TITLE
Block explorer no longer working post .11 update.

### ISSUE THREAD

**Issue by NeuralMiner** [gridcoin-community/BlockExplorer#14]
Due to the RPC changes in .12, the wrapper used to call the wallet no longer works.

**Comment by NeuralMiner** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D2. Do not remove or edit.` [D2|http://app.testquality.com/defect/1745]

**Comment by barton2526** [comment]
Issue resolved by upgrading to 3.7.16.0.

Issue can be closed.
